# Generated by Django 2.2.5 on 2019-10-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Course Name')),
                ('catnum', models.CharField(max_length=90, verbose_name='Catalog Number')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Description')),
                ('cal_year', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90, verbose_name='First Name')),
                ('lname', models.CharField(max_length=90, verbose_name='Last Name')),
                ('facid', models.CharField(max_length=90, verbose_name='Faculty ID')),
                ('facidtype', models.CharField(choices=[('its', 'ITS'), ('other', 'Other')], max_length=90, verbose_name='ID Type')),
                ('role', models.CharField(max_length=90, verbose_name='Faculty Role')),
                ('contact1', models.CharField(max_length=90, verbose_name='Contact 1')),
                ('c1phone', models.CharField(max_length=12, verbose_name='Phone 1')),
                ('c1desc', models.CharField(max_length=90, verbose_name='Desc 1')),
                ('contact2', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact 2')),
                ('c2phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone 2')),
                ('c2desc', models.CharField(blank=True, max_length=90, null=True, verbose_name='Desc 2')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=90, verbose_name='City')),
                ('state', models.CharField(max_length=90, verbose_name='State')),
                ('zipcode', models.CharField(max_length=90, verbose_name='Type')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=90, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Grade')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90, verbose_name='First Name')),
                ('lname', models.CharField(max_length=90, verbose_name='Last Name')),
                ('stuid', models.CharField(max_length=90, verbose_name='Student ID')),
                ('stuidtype', models.CharField(choices=[('its', 'ITS'), ('other', 'Other')], max_length=90, verbose_name='ID Type')),
                ('type', models.CharField(blank=True, max_length=90, null=True, verbose_name='Student Type')),
                ('contact1', models.CharField(max_length=90, verbose_name='Contact 1')),
                ('c1phone', models.CharField(max_length=12, verbose_name='Phone 1')),
                ('c1desc', models.CharField(max_length=90, verbose_name='Desc 1')),
                ('contact2', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact 2')),
                ('c2phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone 2')),
                ('c2desc', models.CharField(blank=True, max_length=90, null=True, verbose_name='Desc 2')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=90, verbose_name='City')),
                ('state', models.CharField(max_length=90, verbose_name='State')),
                ('zipcode', models.CharField(max_length=90, verbose_name='Type')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=90, verbose_name='Gender')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Grade', verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=90, verbose_name='Type')),
                ('transdate', models.DateTimeField(auto_now_add=True, verbose_name='Transaction Date')),
                ('status', models.CharField(max_length=90, verbose_name='Status')),
                ('desc', models.CharField(max_length=90, verbose_name='Description')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval', models.CharField(max_length=90, verbose_name='Evaluation')),
                ('desc', models.CharField(max_length=255, verbose_name='Description')),
                ('score', models.FloatField(blank=True)),
                ('totalscore', models.FloatField(blank=True)),
                ('lettergrade', models.CharField(blank=True, max_length=2, verbose_name='Letter Grade')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Faculty')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infotype', models.CharField(max_length=90, verbose_name='Type')),
                ('desc', models.CharField(blank=True, max_length=90, null=True, verbose_name='Description')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbnjattend.Grade'),
        ),
    ]
