# Generated by Django 2.2.5 on 2019-11-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbnjattend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='c1desc',
            field=models.CharField(max_length=90, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='c2desc',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='zipcode',
            field=models.CharField(max_length=90, verbose_name='Zipcode'),
        ),
        migrations.AlterField(
            model_name='student',
            name='c1desc',
            field=models.CharField(max_length=90, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='student',
            name='c2desc',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zipcode',
            field=models.CharField(max_length=90, verbose_name='Zipcode'),
        ),
    ]
